stages:
  - deploy

.deploy_job:
  image: willhallonline/ansible:2.11-alpine-3.15
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ansible-playbook -v -i ${INVENTORY_FILE} prerequisites.yml
    - ansible-playbook -v -i ${INVENTORY_FILE} ${PLAYBOOK} --extra-vars "gitlab_private_token=$CI_JOB_TOKEN"

Test Update:
  variables:
    INVENTORY_FILE: inventory_TEST.yml
    PLAYBOOK: box/ansible/playbook.yml
  extends: .deploy_job
  only:
    - master
  when: manual

Prod Update:
  variables:
    INVENTORY_FILE: inventory_PROD.yml
    PLAYBOOK: box/ansible/playbook.yml
  extends: .deploy_job
  only:
    - master
  when: manual
