---
- hosts: all
  tasks:
    - name: checkout box locally
      git:
        repo: '{{ cookiecutter.repo_url }}'
        dest: {% raw %}'{{ inventory_dir }}/box'{% endraw %}
        force: yes
        version: {% raw %}'{{ box_version | default("master") }}'{% endraw %}
      delegate_to: localhost
    
    - name: install required ansible-galaxy roles
      shell: ansible-galaxy install -r box/ansible/requirements.yml
      delegate_to: localhost
