name: Initialize box from template
on:
  push:
    paths:
      - box-config.yaml
jobs:
  init:
    name: Reinitialize repository
    runs-on: ubuntu-latest
    steps:
      - name: Exit for template repository
        shell: bash
        run: |
          curl --silent -X GET \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/json" \
          $GITHUB_API_URL/repos/$GITHUB_REPOSITORY \
          | jq --exit-status '.is_template == false'

      - uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install cookiecutter
        run: pip install cookiecutter

      - name: Create cookiecutter.json
        shell: bash
        run: |
          yq ".box_name = \"${{ github.event.repository.name }}\" | .short_name = \"{{ cookiecutter.box_name | replace('-box', '') }}\" | .repo_url = \"${{ github.server_url }}/${{ github.repository }}\"" \
          -o json box-config.yaml > cookiecutter.json

      - name: Scaffolding repository
        shell: bash
        run: cat cookiecutter.json && cookiecutter --no-input --output-dir ./tmp-repo .

      - name: Prepare new directory structure and remove unnecessary files
        shell: bash
        run: |
          find ./ -maxdepth 1 \
          ! -name '.' ! -name '.git' ! -name 'tmp-repo' \
          -exec rm -rf {} +

      - name: Copy repo files
        shell: bash
        run: rsync -r ./tmp-repo/*/ . && rm -rf ./tmp-repo && ls -l

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Initialized box"
